### ISSUE TITLE
Unable to reconfigure integration on 2023.6.0 beta

### ISSUE THREAD

**Issue by krazos** [bretterer/home-assistant-rivian#104]
I'm running 2023.6.0b5, and I am unable to reconfigure the Rivian integration from the new integration page as there is no `CONFIGURE` button. I'm not sure if it's related to the recent patch to fix the initial configuration bug, or because it's shown as a "Hub" rather than an "Integration entry" on the integration page.

In any event, I was trying to switch Rivian logins this morning to test the wall charger sensors, which are linked to a different account, and I ended up having to manually edit `core.config_entries` to change the username and password.

Screenshots below of the Rivian integration page and the Alexa Media Player integration page for reference.

![image](https://github.com/bretterer/home-assistant-rivian/assets/18428022/5a24c91d-8a6b-4c7e-a199-b6f1c85075bf)

![image](https://github.com/bretterer/home-assistant-rivian/assets/18428022/6b9bc768-b07d-4749-9fe1-78c9b1a080d7)

**Comment by natekspencer** [comment]
The configure option was removed as part of allowing for multiple VINs as the need for it became mostly irrelevant.

**Comment by tmack8001** [comment]
@natekspencer shouldn't we still allow for the username/password used to be changed post initial configuration? Sure not promoting for a VIN change anymore, but a different user account should be able to be supported. Maybe we removed the entire flow vs a specific step?

One thing to do is just remove the integration and re-add it?

**Comment by natekspencer** [comment]
You should be able to add multiple integrations

**Comment by natekspencer** [comment]
> Thanks for the feedback. Are either of those workarounds non-destructive? In other words, if I have renamed, hidden and/or disabled certain entities, will those properties be restored upon removing and re-adding the integration with a different Rivian account? And wouldn't adding a second instance of the integration with a different account linked to the same vehicle duplicate all of the sensors?

Removing/re-adding will restore the defaults of the integration. So any hidden/disabled/re-named entities will be reverted and you would have to make those changes again. The non-destructive path to switch accounts and retain customizations is:
1. Disable the current instance of this integration
2. Add a new instance with the account you are changing to
   - Because VIN is used as the identifier, it will match any "duplicates" to the existing disabled integration and not duplicate entities
   - You'll kind of be in a funky state in that the devices from the new instance will also appear as disabled because they are disabled in the previous config entry, which is why step 4 is important
3. Delete the disabled instance
4. Disable and then enable the new instance of this integration
5. Reload the integration

OR

1. Change the password on your Rivian account
   - This will cause the session to become invalid and trigger you to re-authenticate in Home Assistant
2. Update your credentials to the new username/password in Home Assistant


> It's not clear to me why we wouldn't want to give users the option to re-configure the integration in order to change the username and password

Typically, you don't re-configure an integration to change the underlying account as that creates a different set of issues (invalid/missing/unavailable devices/entities). Previously, this was allowed because multiple VINs were not supported and only one instance was allowed.
