### ISSUE TITLE
Service mode results in incorrect data for many sensors

### ISSUE THREAD

**Issue by alterbridge86** [bretterer/home-assistant-rivian#139]
My truck at the SC being fixed, and the techs put it in service mode for the first time. This resulted in many of the sensors going "unavailable" (understandable and expected), but many others are now showing completely incorrect data (e.g. all of the doors are open, windows down, every heated seat is on, it's in car wash mode, it's charging, cabin preconditioning is running, etc).

Not sure what specific data I can provide to help diagnose and handle these scenarios, just let me know and happy to upload it.

**Comment by natekspencer** [comment]
If you have the beta installed, you should be able to download a diagnostics file that would help here. I can't remember if we ported it to the 0.10.x releases or not. Otherwise, on those you should be able to enable debug logging and restart the integration so we can get the data points that are incorrect.

**Comment by alterbridge86** [comment]
I'm still on the latest 0.10.x release, I toggled debug logging and restarted the integration. 

I have intentions of moving to the beta once I had a working truck :) If the diagnostic bundle is more useful, happy to update to the beta now as long as I don't need the vehicle here to re-connect anything.

[home-assistant_rivian_2023-12-15T03-52-10.095Z.log](https://github.com/bretterer/home-assistant-rivian/files/13680740/home-assistant_rivian_2023-12-15T03-52-10.095Z.log)

**Comment by natekspencer** [comment]
The upgrade to beta should be seamless and doesn't require your vehicle to be present unless you want to enable vehicle controls. This log looks like it might be returning a very small subset of data, so the diagnostics download would probably be better here

**Comment by alterbridge86** [comment]
Done! This doesn't seem to offer up a lot of info either...seems the API isn't returning values for a lot of the data I'm seeing, so I'm not sure where it's coming from. 

For example I see the Charger Connection entity flipped to "Plugged In" at 4:01p EST on 12/13. Service mode was turned on at 11:39a, so it doesn't directly coincide with that happening. Maybe the API replied with some bogus data at some point yesterday, and now it's just gotten cached in my HA instance?

[config_entry-rivian-9724af48d8184783ba115acd19f5252a.json.txt](https://github.com/bretterer/home-assistant-rivian/files/13680868/config_entry-rivian-9724af48d8184783ba115acd19f5252a.json.txt)

**Comment by natekspencer** [comment]
This tracks with what I was suspecting after seeing your logs. When in Service Mode, it looks like you only get location and service mode data from the subscription updates. We have some sensors that look for a specific value for `on` while others look for `off` which is why you see weird results depending on if the key is there or not as well. We'll probably have to test around with Service Mode ourselves before we're able to properly address it.

**Comment by natekspencer** [comment]
@alterbridge86  Can you see any info about your vehicle when you open the app or does it just say it is in service mode?

**Comment by alterbridge86** [comment]
Makes sense, the diagnostic output was super helpful. Had I seen that initially I wouldn't have raised this issue since it's clear the graphql doesn't contain any additional information beyond the service mode status and location. 

Nope, no info about the vehicle in the app. Just says "In Service" with a rear view look at the vehicle. I also have the option to check the location, which tracks with the two bits of info we're seeing in the logs here.
